### ISSUE TITLE
Consider migrating to the ember-codemods org?

### ISSUE THREAD

**Issue by rwjblue** [ember-codemods/es5-getter-ember-codemod#25]
I’ve slowly been moving the general community codemods that I’ve made into the ember-codemods GitHub org. Mostly as a way to:

* increase visibility 
* reduce bus factor

We’d make sure to preserve the current permissions (e.g. no reduction in control) if we did the transition.

Would this be something y’all would be open to? If not, no worries! Please feel free to close this issue.

**Comment by rwjblue** [comment]
@rondale-sc - I believe that I've already shot you over an invite to the org, so if you are in favor you should be able to transfer.

**Comment by efx** [comment]
@rwjblue I think we can close this. Thanks for initiating!
